# Jupyter Notebook for Counting Building Occupancy from Polaris Traffic Simulation Data

This notebook will load a Polaris SQLlite data file into a Pandas data frame using sqlite3 libraries and count the average number of people in each building in each hour of the simulation.

For help with Jupyter notebooks

For help on using sql with Pandas see
http://www.pererikstrandberg.se/blog/index.cgi?page=PythonDataAnalysisWithSqliteAndPandas

For help  on data analysis with Pandas see
http://nbviewer.jupyter.org/github/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/Index.ipynb

In [9]:
import sqlite3
import pandas as pd

In [10]:
# Create your connection.
cnx = sqlite3.connect('detroit-Demand.sqlite')

In [11]:
cnx

In [37]:
households = pd.read_sql_query("SELECT household, location FROM Household", cnx)

In [13]:
households

,household,hhold,location,persons,workers,vehicles,type,income
0,1,2013000096625,72764,1,0,1,1,40040
1,2,2012000826736,72977,1,0,1,1,30000
2,3,2012000649125,72947,1,0,0,1,7800
3,4,2012000015353,72926,3,0,0,1,54300
4,5,2012000003126,72967,3,1,1,1,54100
5,6,2012000001917,72965,2,2,2,1,169000
6,7,2013000842149,72948,1,0,0,1,33200
7,8,2013000716469,72956,1,0,1,1,90000
8,9,2012001265201,72955,1,0,1,1,50000
9,10,2012000042358,72765,1,0,1,1,13900
10,11,2012000121072,72957,2,1,2,1,20000
11,12,2013000469670,72967,3,2,1,1,33000
12,13,2013001110335,72970,2,2,2,1,44000
13,14,2012000062209,72924,2,0,1,1,31100
14,15,2012000136059,72965,1,0,2,1,6000
15,16,2012000174338,72926,4,1,2,1,24000
16,17,2012000459091,72762,2,0,2,1,84200
17,18,2012001221456,72925,2,2,2,1,115000
18,19,2012001456950,72977,2,0,1,1,12400
19,20,2013000419605,72955,4,1,3,1,203200
20,21,2012000000359,43091,1,0,0,1,17200
21,22,2013001317565,43091,3,2,3,1,118000
22,23,2013000731403,43064,4,2,2,1,175000
23,24,2012000007723,43090,4,2,2,1,37000
24,25,2013001267902,41909,2,2,4,1,271000
25,26,2012000001917,42979,2,2,2,1,169000
26,27,2012000012073,43006,1,0,1,1,31500
27,28,2012000042358,43053,1,0,1,1,13900
28,29,2012000050387,43129,5,2,2,1,106000
29,30,2012000136059,42969,1,0,2,1,6000
...,...,...,...,...,...,...,...,...
18910,18911,2013001422804,69185,1,0,1,1,20300
18911,18912,2012000426983,69234,2,1,1,1,54800
18912,18913,2012000103980,69177,2,0,1,1,109000
18913,18914,2012000128774,69215,1,0,1,1,28000
18914,18915,2012000245428,69179,2,0,2,1,91000
18915,18916,2012000811866,66873,1,0,1,1,15400
18916,18917,2012000007825,66908,1,0,0,1,8570
18917,18918,2013000050059,68761,1,0,1,1,3500
18918,18919,2012000027754,66873,3,1,1,1,36000
18919,18920,2013000742211,66862,3,2,3,1,54100
18920,18921,2013000513602,68800,3,2,2,1,40000
18921,18922,2013000650928,66942,4,3,3,1,158300
18922,18923,2012000023471,66937,4,2,2,1,68200
18923,18924,2013000968099,68774,1,0,0,3,0
18924,18925,2013000221578,66772,1,0,0,2,0
18925,18926,2013000071575,68761,1,0,0,2,0
18926,18927,2012000284714,66774,1,0,0,2,0
18927,18928,2012000046421,66937,1,0,0,3,0
18928,18929,2012000049431,66907,1,0,1,1,36100
18929,18930,2012000321940,66850,2,1,2,1,20000
18930,18931,2012001465165,66983,2,0,1,1,70500
18931,18932,2012001051889,66982,2,1,2,1,45500
18932,18933,2012000503605,66891,2,2,2,1,70100
18933,18934,2012000097420,66906,3,1,1,1,28000
18934,18935,2012000103980,66908,2,0,1,1,109000
18935,18936,2013001078027,66873,1,0,0,1,8700
18936,18937,2012000143873,66882,4,1,1,1,2000
18937,18938,2012000229440,66982,3,0,0,1,9600
18938,18939,2012000256579,66937,2,2,0,1,37100
18939,18940,2012000344947,66870,3,2,2,1,19100

In [14]:
people = pd.read_sql_query("SELECT * FROM Person", cnx)

In [15]:
locations = pd.read_sql_query("SELECT * FROM All_Locations", cnx)

In [16]:
locations

,location,link,dir,offset,setback,zone,truck_org,truck_des,auto_org,auto_des,...,land_use,geo,household,hhold,location:1,persons,workers,vehicles,type,income
0,1,16683,1,1398.762944,26.212315,84,1.0,1.0,1.0,1.0,...,SPECIAL_GEN,b'\x00\x01%i\x00\x00\xab\x19L\xb1zl\x14A\x06\x...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,10289,0,369.298210,46.117645,260,1.0,1.0,1.0,1.0,...,BUSINESS,b'\x00\x01%i\x00\x00-\t&\x05\xfc\x9d\x13A\x19]...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,10277,0,75.808450,27.047637,260,1.0,1.0,1.0,1.0,...,BUSINESS,b'\x00\x01%i\x00\x00\x80\xadp\xba\x00\x9d\x13A...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,10277,0,336.276404,216.550644,260,1.0,1.0,1.0,1.0,...,BUSINESS,b'\x00\x01%i\x00\x00\x97\xd2s\x9c\xb7\xa1\x13A...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,10273,1,1617.558110,30.999018,260,1.0,1.0,1.0,1.0,...,BUSINESS,b'\x00\x01%i\x00\x00r\x0fgG)\x9c\x13A\xf96vl\x...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,6,10273,1,1504.448484,29.648675,260,1.0,1.0,1.0,1.0,...,BUSINESS,b'\x00\x01%i\x00\x00\xe1\xc8cC&\x9d\x13A\x99{\...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7,10277,0,437.175634,216.959517,260,1.0,1.0,1.0,1.0,...,BUSINESS,b'\x00\x01%i\x00\x00=4\x8e\x8a\x97\xa2\x13Aj^\...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,8,10277,0,314.049382,26.011619,260,1.0,1.0,1.0,1.0,...,BUSINESS,b'\x00\x01%i\x00\x00\xb1x\xd4\xc9\n\x9f\x13A\x...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,9,10277,0,415.713697,45.624699,260,1.0,1.0,1.0,1.0,...,BUSINESS,"b'\x00\x01%i\x00\x00p\x82\xaf|,\xa0\x13A%T\xc5...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,10,11123,0,457.391475,26.335591,260,1.0,1.0,1.0,1.0,...,BUSINESS,b'\x00\x01%i\x00\x00IR\x19\x83\xcb\xa8\x13A\xe...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,11,11123,1,274.906773,24.311842,259,1.0,1.0,1.0,1.0,...,BUSINESS,b'\x00\x01%i\x00\x00\xd4\xd7\xc2\xd9\x90\xaa\x...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,12,10277,0,522.480213,27.840760,260,1.0,1.0,1.0,1.0,...,BUSINESS,b'\x00\x01%i\x00\x00\xe0\x1f;\xa7\xdc\xa0\x13A...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,13,11123,0,420.818300,26.553238,260,1.0,1.0,1.0,1.0,...,BUSINESS,b'\x00\x01%i\x00\x00S\xdb\x17BQ\xa8\x13A\x919\...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,14,10277,0,618.937477,27.885972,260,1.0,1.0,1.0,1.0,...,BUSINESS,b'\x00\x01%i\x00\x00\x12SY\x92\xb1\xa1\x13A~\x...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,15,11123,1,627.168405,24.658415,259,1.0,1.0,1.0,1.0,...,BUSINESS,b'\x00\x01%i\x00\x00\xc3\x0b\xee\xc0\xfc\xa5\x...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,16,11123,0,104.956410,15.255817,260,1.0,1.0,1.0,1.0,...,BUSINESS,b'\x00\x01%i\x00\x00`\x8d\x8f\xa1N\xa4\x13A\t\...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,17,10277,0,788.095955,27.375435,260,1.0,1.0,1.0,1.0,...,BUSINESS,b'\x00\x01%i\x00\x00plj\x00%\xa3\x13A\x9a2\xfd...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,18,11123,1,730.041882,14.289672,259,1.0,1.0,1.0,1.0,...,BUSINESS,b'\x00\x01%i\x00\x00\x81\x9cv?\x8f\xa4\x13As`/...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,19,10273,1,1011.704229,24.291529,260,1.0,1.0,1.0,1.0,...,BUSINESS,b'\x00\x01%i\x00\x00\xa9\x84\xdd\x97r\xa1\x13A...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,20,10274,0,60.132157,26.149550,259,1.0,1.0,1.0,1.0,...,BUSINESS,"b""\x00\x01%i\x00\x00v'J\xed\xed\xa3\x13A\xee\x...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,21,10274,0,187.739465,26.439197,259,1.0,1.0,1.0,1.0,...,BUSINESS,b'\x00\x01%i\x00\x00\x9cw\xc0\x82\x05\xa5\x13A...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,22,10274,0,266.222896,60.806642,259,1.0,1.0,1.0,1.0,...,BUSINESS,b'\x00\x01%i\x00\x00\x9a\xf0\x8f\r$\xa6\x13AkL...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,23,10273,1,707.796795,14.376104,259,1.0,1.0,1.0,1.0,...,BUSINESS,b'\x00\x01%i\x00\x00\xf1]\xb7V/\xa4\x13A`\x92\...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,24,10273,1,658.507008,25.150614,259,1.0,1.0,1.0,1.0,...,BUSINESS,b'\x00\x01%i\x00\x00\xff\xec\xf4\x98w\xa4\x13A...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,25,10274,0,516.871604,211.853018,259,1.0,1.0,1.0,1.0,...,BUSINESS,b'\x00\x01%i\x00\x002\x94\xe9\x8cA\xaa\x13Ao\x...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,26,10273,1,567.061442,25.452744,259,1.0,1.0,1.0,1.0,...,BUSINESS,b'\x00\x01%i\x00\x00U\x17\xcew?\xa5\x13Ax0b#n\...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,27,10274,0,350.260614,26.077824,259,1.0,1.0,1.0,1.0,...,BUSINESS,b'\x00\x01%i\x00\x00e\x81j$g\xa6\x13A\xfb}\xf2...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,28,10274,0,734.283985,509.108151,259,1.0,1.0,1.0,1.0,...,BUSINESS,b'\x00\x01%i\x00\x00(]\xfb\x81\x00\xb0\x13A\x8...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,29,10273,1,511.632988,15.054771,259,1.0,1.0,1.0,1.0,...,BUSINESS,b'\x00\x01%i\x00\x00\xd3\xfd\xc4\xfc\xdb\xa5\x...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,30,10274,0,495.564056,25.449682,259,1.0,1.0,1.0,1.0,...,BUSINESS,b'\x00\x01%i\x00\x00\xac\x96\x82I\xa2\xa7\x13A...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148499,182611,459,1,323.939104,167.504554,2752,1.0,1.0,1.0,1.0,...,RESIDENTIAL-SINGLE,b'\x00\x01%i\x00\x00\xce\xaf\xb9\x8b\x13\x08\x...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148500,182612,464,1,133.124887,101.704880,2780,1.0,1.0,1.0,1.0,...,RESIDENTIAL-SINGLE,b'\x00\x01%i\x00\x00\x07\x18v\xc0t\x16\x0eA$2t...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148501,182614,464,0,938.407128,186.627515,2752,1.0,1.0,1.0,1.0,...,RESIDENTIAL-SINGLE,b'\x00\x01%i\x00\x00\xbd\x84@\xdf\x05\r\x0eAa\...,4195.0,2.012000e+12,182614.0,5.0,3.0,4.0,1.0,77600.0
148502,182615,464,1,566.482052,2.727448,2780,1.0,1.0,1.0,1.0,...,RESIDENTIAL-SINGLE,b'\x00\x01%i\x00\x00\xe1@j\xf2\xf5\x12\x0eA\x1...,4197.0,2.013000e+12,182615.0,2.0,0.0,1.0,1.0,33000.0
148503,182617,464,0,435.919617,128.950485,2752,1.0,1.0,1.0,1.0,...,RESIDENTIAL-SINGLE,b'\x00\x01%i\x00\x00\xc5-\xebB[\x0e\x0eAI/\xe8...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148504,182618,464,1,1131.551580,206.707920,2780,1.0,1.0,1.0,1.0,...,RESIDENTIAL-SINGLE,b'\x00\x01%i\x00\x00\xdc\xaf\x11R\xce\x18\x0eA...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148505,182623,457,0,290.476718,103.360349,2780,1.0,1.0,1.0,1.0,...,RESIDENTIAL-SINGLE,"b'\x00\x01%i\x00\x00\xc0cP\xa0!\x15\x0eA\x0eR,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148506,182627,262,1,853.259273,157.397859,2744,1.0,1.0,1.0,1.0,...,RESIDENTIAL-SINGLE,b'\x00\x01%i\x00\x00\xeb%k\xc3}\xaa\x0eA:\xbc\...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148507,182628,262,1,1032.642075,312.831023,2753,1.0,1.0,1.0,1.0,...,RESIDENTIAL-SINGLE,b'\x00\x01%i\x00\x00ED]\x07<\xa3\x0eA\xbf@\x9c...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148508,182631,455,0,2310.074547,306.252887,2752,1.0,1.0,1.0,1.0,...,RESIDENTIAL-SINGLE,b'\x00\x01%i\x00\x00\x8d\x17S[\x9c\xcb\rAU\x96...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148509,182632,455,1,1378.247026,5.365943,2752,1.0,1.0,1.0,1.0,...,RESIDENTIAL-SINGLE,b'\x00\x01%i\x00\x00\\\xed\xad\xee\xb6\xae\rA\...,4192.0,2.012000e+12,182632.0,5.0,2.0,5.0,1.0,95700.0
148510,182633,457,0,4023.404370,19.592795,2780,1.0,1.0,1.0,1.0,...,RESIDENTIAL-SINGLE,b'\x00\x01%i\x00\x00\xbbqT\xf3\x1e\x13\x0eA\xb...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148511,182634,454,1,7223.672532,190.545269,2752,1.0,1.0,1.0,1.0,...,RESIDENTIAL-SINGLE,b'\x00\x01%i\x00\x00\xdb\x9d\xa9\xe2w\xd7\rA~\...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148512,182637,455,0,486.857583,109.150358,2752,1.0,1.0,1.0,1.0,...,RESIDENTIAL-SINGLE,b'\x00\x01%i\x00\x00\x9f\x8c!a\xe0\x96\rAnU\x9...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148513,182646,10783,0,118.060067,161.911807,442,1.0,1.0,1.0,1.0,...,ALL,b'\x00\x01%i\x00\x00\xb7\xcc\xa9\xa7uc\x13A\x0...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148514,182647,110488,1,283.370321,96.707525,2160,1.0,1.0,1.0,1.0,...,ALL,b'\x00\x01%i\x00\x00\xd5v\xfc\x9f\xa4\xc9\x10A...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148515,182648,24385,1,0.000000,5613.431510,3001,1.0,1.0,1.0,1.0,...,ALL,b'\x00\x01%i\x00\x00\xd0]\xb5\x18\nj\x16A\xc6c...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148516,182649,23216,1,6302.542678,5488.461064,3002,1.0,1.0,1.0,1.0,...,ALL,b'\x00\x01%i\x00\x00s1\x15Z0K\x14ADI\x1f\xfd\x...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148517,182650,6331,0,1196.970264,5879.938437,3004,1.0,1.0,1.0,1.0,...,ALL,b'\x00\x01%i\x00\x00\x1d\xc4\x14\x1b\x13\x81\x...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148518,182651,736,0,3734.762300,6265.045616,3005,1.0,1.0,1.0,1.0,...,ALL,b'\x00\x01%i\x00\x00H\xe3+n\xb2\xa7\x0eA\x05hU...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148519,182652,424,0,0.000000,4526.603751,3006,1.0,1.0,1.0,1.0,...,ALL,b'\x00\x01%i\x00\x00AZYC\xff\xf9\x0cA3\xab\x80...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148520,182653,455,0,0.000000,4578.086201,3007,1.0,1.0,1.0,1.0,...,ALL,b'\x00\x01%i\x00\x00@\xb3rO\xdb\xfc\x0cA\x1c7]...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148521,182654,273,0,0.000000,4857.044394,3008,1.0,1.0,1.0,1.0,...,ALL,b'\x00\x01%i\x00\x00h\xbb\x8c\xe8\xad\xff\x0cA...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148522,182655,83,0,0.000000,4054.258969,3009,1.0,1.0,1.0,1.0,...,ALL,b'\x00\x01%i\x00\x00k!\xaa\xd7\xe7\xf2\x0cA\xf...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148523,182656,1740,0,0.000000,3487.461679,3011,1.0,1.0,1.0,1.0,...,ALL,b'\x00\x01%i\x00\x00?|\xd1\x013\xda\x0fA\x01G\...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148524,182657,845,0,939.486592,3512.802283,3013,1.0,1.0,1.0,1.0,...,ALL,b'\x00\x01%i\x00\x00\x99/\xb6=\x02\xdf\x10A+\x...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148525,182658,20628,1,0.000000,5140.813921,3015,1.0,1.0,1.0,1.0,...,ALL,b'\x00\x01%i\x00\x00\x91\x87\xfe\xfbEw\x13A-\x...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148526,182659,23257,0,3168.962453,5189.129143,3016,1.0,1.0,1.0,1.0,...,ALL,b'\x00\x01%i\x00\x00\xc2al\x8f\xf7/\x15A@\x8c\...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148527,182660,13871,0,510.699377,1796.802178,3017,1.0,1.0,1.0,1.0,...,ALL,"b'\x00\x01%i\x00\x00&3""q\x1a5\x14A\xc1\xd5\xa8...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148528,182661,24592,0,49.684342,1978.164660,3018,1.0,1.0,1.0,1.0,...,ALL,b'\x00\x01%i\x00\x00\xbaeY\xd2\x01\x8a\x17A\x9...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
activity = pd.read_sql_query("SELECT * FROM Activity", cnx)

In [18]:
people

,person,id,school_location_id,work_location_id,age,worker_class,education,industry,employment,gender,...,journey_to_work_arrival_time,journey_to_work_mode,journey_to_work_travel_time,journey_to_work_vehicle_occupancy,marital_status,race,school_enrollment,school_grade_level,work_hours,household
0,1,0,0,152395,27,1,21,6870,1,1,...,470,1,30,1,5,1,1,0,45,1
1,2,0,0,157591,42,1,19,8180,1,1,...,455,1,19,1,4,2,1,0,40,2
2,3,0,0,0,43,0,16,0,6,1,...,477,0,0,0,5,1,1,0,0,3
3,4,0,0,0,76,0,20,0,6,1,...,494,0,0,0,1,1,1,0,0,4
4,5,1,0,0,76,0,16,0,6,2,...,484,0,0,0,1,1,1,0,0,4
5,6,2,0,0,51,0,18,0,6,1,...,461,0,0,0,5,1,1,0,0,4
6,7,0,0,0,94,0,15,0,6,1,...,490,0,0,0,1,1,1,0,0,5
7,8,1,0,0,94,0,16,0,6,2,...,475,0,0,0,1,1,1,0,0,5
8,9,2,0,6869,56,6,16,8370,1,1,...,514,11,0,0,3,1,1,0,12,5
9,10,0,0,40488,28,1,21,7470,1,2,...,515,1,35,1,1,1,1,0,45,6
10,11,1,0,72638,29,1,21,3570,1,1,...,540,1,35,1,1,1,1,0,45,6
11,12,0,0,0,83,0,16,0,6,2,...,429,0,0,0,2,1,1,0,0,7
12,13,0,0,67645,34,1,20,3895,1,2,...,495,1,15,1,5,1,1,0,50,8
13,14,0,0,151158,51,2,16,8190,1,2,...,500,1,50,1,5,1,1,0,40,9
14,15,0,0,41628,34,2,22,7680,1,2,...,329,1,17,1,5,2,1,0,32,10
15,16,0,47207,0,29,1,21,2670,6,1,...,426,0,0,0,1,2,3,16,50,11
16,17,1,0,0,25,0,21,0,6,2,...,467,0,0,0,1,2,1,0,0,11
17,18,0,0,59264,37,2,16,8180,1,2,...,450,1,30,1,5,2,1,0,40,12
18,19,1,73652,67559,18,1,18,7690,1,1,...,940,1,9,1,5,2,2,15,40,12
19,20,2,146397,0,16,9,12,9920,3,2,...,445,0,0,0,5,2,2,12,0,12
20,21,0,41799,74423,24,1,21,8590,1,2,...,324,1,9,1,5,1,2,16,44,13
21,22,1,0,63320,25,1,16,4970,1,2,...,340,1,25,1,5,1,1,0,40,13
22,23,0,0,0,57,0,20,0,6,2,...,471,0,0,0,3,1,1,0,0,14
23,24,1,0,0,21,0,17,0,6,2,...,498,0,0,0,5,1,1,0,0,14
24,25,0,0,0,32,1,19,770,3,1,...,514,0,0,0,3,1,1,0,40,15
25,26,0,0,0,23,1,13,5580,6,2,...,498,0,0,0,5,1,1,0,20,16
26,27,1,141697,0,6,0,3,0,0,2,...,515,0,0,0,5,1,2,2,0,16
27,28,2,0,0,0,0,0,0,0,1,...,500,0,0,0,5,1,0,0,0,16
28,29,3,0,151284,24,1,14,6290,1,1,...,350,1,19,1,5,1,1,0,55,16
29,30,0,0,72558,64,1,16,7970,1,2,...,405,1,30,1,3,1,1,0,60,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46411,46412,0,0,0,74,0,16,0,6,2,...,438,0,0,0,2,1,1,0,0,18926
46412,46413,0,0,0,90,0,14,0,6,1,...,526,0,0,0,2,1,1,0,0,18927
46413,46414,0,0,0,58,0,14,0,6,2,...,533,0,0,0,4,1,1,0,0,18928
46414,46415,0,0,0,68,0,21,0,6,1,...,510,0,0,0,5,1,1,0,0,18929
46415,46416,0,0,68568,67,1,19,7680,1,1,...,1420,1,19,1,1,1,1,0,40,18930
46416,46417,1,0,0,61,1,18,9290,6,2,...,424,0,0,0,1,1,1,0,0,18930
46417,46418,0,0,0,76,0,23,0,6,1,...,455,0,0,0,1,1,1,0,0,18931
46418,46419,1,0,0,77,0,19,0,6,2,...,470,0,0,0,1,1,1,0,0,18931
46419,46420,0,0,0,56,0,19,0,6,1,...,536,0,0,0,1,1,1,0,0,18932
46420,46421,1,0,66724,56,1,16,8190,1,2,...,390,1,60,1,1,1,1,0,36,18932
46421,46422,0,0,43403,48,2,18,770,1,1,...,400,1,39,1,1,1,1,0,40,18933
46422,46423,1,0,40835,48,1,18,8370,1,2,...,490,1,55,1,1,1,1,0,40,18933
46423,46424,0,0,44047,30,1,20,8090,1,2,...,460,1,9,1,5,1,1,0,40,18934
46424,46425,1,67085,0,5,0,1,0,0,1,...,506,0,0,0,5,1,2,1,0,18934
46425,46426,2,70250,0,5,0,1,0,0,2,...,447,0,0,0,5,1,2,1,0,18934
46426,46427,0,0,0,69,0,22,0,6,2,...,526,0,0,0,5,1,1,0,0,18935
46427,46428,1,0,0,94,0,16,0,6,2,...,537,0,0,0,2,1,1,0,0,18935
46428,46429,0,0,0,41,0,17,0,6,1,...,535,0,0,0,3,1,1,0,0,18936
46429,46430,0,0,0,35,1,19,5170,3,2,...,439,0,0,0,5,1,1,0,36,18937
46430,46431,1,51305,0,14,0,10,0,0,1,...,530,0,0,0,5,9,2,10,0,18937
46431,46432,2,70242,0,11,0,6,0,0,1,...,503,0,0,0,5,1,2,6,0,18937
46432,46433,3,76625,0,7,0,3,0,0,2,...,420,0,0,0,5,2,2,3,0,18937
46433,46434,0,0,0,45,7,16,470,3,1,...,521,0,0,0,5,1,1,0,0,18938
46434,46435,1,76583,0,6,0,3,0,0,1,...,465,0,0,0,5,1,2,2,0,18938
46435,46436,2,0,0,50,9,16,9920,3,2,...,492,0,0,0,3,1,1,0,0,18938
46436,46437,0,0,76715,38,6,17,7690,1,2,...,510,1,30,1,5,2,1,0,32,18939
46437,46438,1,0,69737,34,1,16,4980,1,1,...,1420,1,19,1,5,2,1,0,37,18939
46438,46439,0,0,66719,46,1,13,6170,1,1,...,510,1,2,1,1,1,1,0,20,18940
46439,46440,1,0,0,44,0,12,0,6,2,...,484,0,0,0,1,1,1,0,0,18940
46440,46441,2,8003,76190,17,1,15,4980,1,1,...,895,1,9,1,5,1,2,14,14,18940

In [19]:
locations

,location,link,dir,offset,setback,zone,truck_org,truck_des,auto_org,auto_des,...,land_use,geo,household,hhold,location:1,persons,workers,vehicles,type,income
0,1,16683,1,1398.762944,26.212315,84,1.0,1.0,1.0,1.0,...,SPECIAL_GEN,b'\x00\x01%i\x00\x00\xab\x19L\xb1zl\x14A\x06\x...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,10289,0,369.298210,46.117645,260,1.0,1.0,1.0,1.0,...,BUSINESS,b'\x00\x01%i\x00\x00-\t&\x05\xfc\x9d\x13A\x19]...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,10277,0,75.808450,27.047637,260,1.0,1.0,1.0,1.0,...,BUSINESS,b'\x00\x01%i\x00\x00\x80\xadp\xba\x00\x9d\x13A...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,10277,0,336.276404,216.550644,260,1.0,1.0,1.0,1.0,...,BUSINESS,b'\x00\x01%i\x00\x00\x97\xd2s\x9c\xb7\xa1\x13A...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,10273,1,1617.558110,30.999018,260,1.0,1.0,1.0,1.0,...,BUSINESS,b'\x00\x01%i\x00\x00r\x0fgG)\x9c\x13A\xf96vl\x...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,6,10273,1,1504.448484,29.648675,260,1.0,1.0,1.0,1.0,...,BUSINESS,b'\x00\x01%i\x00\x00\xe1\xc8cC&\x9d\x13A\x99{\...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7,10277,0,437.175634,216.959517,260,1.0,1.0,1.0,1.0,...,BUSINESS,b'\x00\x01%i\x00\x00=4\x8e\x8a\x97\xa2\x13Aj^\...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,8,10277,0,314.049382,26.011619,260,1.0,1.0,1.0,1.0,...,BUSINESS,b'\x00\x01%i\x00\x00\xb1x\xd4\xc9\n\x9f\x13A\x...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,9,10277,0,415.713697,45.624699,260,1.0,1.0,1.0,1.0,...,BUSINESS,"b'\x00\x01%i\x00\x00p\x82\xaf|,\xa0\x13A%T\xc5...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,10,11123,0,457.391475,26.335591,260,1.0,1.0,1.0,1.0,...,BUSINESS,b'\x00\x01%i\x00\x00IR\x19\x83\xcb\xa8\x13A\xe...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,11,11123,1,274.906773,24.311842,259,1.0,1.0,1.0,1.0,...,BUSINESS,b'\x00\x01%i\x00\x00\xd4\xd7\xc2\xd9\x90\xaa\x...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,12,10277,0,522.480213,27.840760,260,1.0,1.0,1.0,1.0,...,BUSINESS,b'\x00\x01%i\x00\x00\xe0\x1f;\xa7\xdc\xa0\x13A...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,13,11123,0,420.818300,26.553238,260,1.0,1.0,1.0,1.0,...,BUSINESS,b'\x00\x01%i\x00\x00S\xdb\x17BQ\xa8\x13A\x919\...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,14,10277,0,618.937477,27.885972,260,1.0,1.0,1.0,1.0,...,BUSINESS,b'\x00\x01%i\x00\x00\x12SY\x92\xb1\xa1\x13A~\x...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,15,11123,1,627.168405,24.658415,259,1.0,1.0,1.0,1.0,...,BUSINESS,b'\x00\x01%i\x00\x00\xc3\x0b\xee\xc0\xfc\xa5\x...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,16,11123,0,104.956410,15.255817,260,1.0,1.0,1.0,1.0,...,BUSINESS,b'\x00\x01%i\x00\x00`\x8d\x8f\xa1N\xa4\x13A\t\...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,17,10277,0,788.095955,27.375435,260,1.0,1.0,1.0,1.0,...,BUSINESS,b'\x00\x01%i\x00\x00plj\x00%\xa3\x13A\x9a2\xfd...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,18,11123,1,730.041882,14.289672,259,1.0,1.0,1.0,1.0,...,BUSINESS,b'\x00\x01%i\x00\x00\x81\x9cv?\x8f\xa4\x13As`/...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,19,10273,1,1011.704229,24.291529,260,1.0,1.0,1.0,1.0,...,BUSINESS,b'\x00\x01%i\x00\x00\xa9\x84\xdd\x97r\xa1\x13A...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,20,10274,0,60.132157,26.149550,259,1.0,1.0,1.0,1.0,...,BUSINESS,"b""\x00\x01%i\x00\x00v'J\xed\xed\xa3\x13A\xee\x...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,21,10274,0,187.739465,26.439197,259,1.0,1.0,1.0,1.0,...,BUSINESS,b'\x00\x01%i\x00\x00\x9cw\xc0\x82\x05\xa5\x13A...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,22,10274,0,266.222896,60.806642,259,1.0,1.0,1.0,1.0,...,BUSINESS,b'\x00\x01%i\x00\x00\x9a\xf0\x8f\r$\xa6\x13AkL...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,23,10273,1,707.796795,14.376104,259,1.0,1.0,1.0,1.0,...,BUSINESS,b'\x00\x01%i\x00\x00\xf1]\xb7V/\xa4\x13A`\x92\...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,24,10273,1,658.507008,25.150614,259,1.0,1.0,1.0,1.0,...,BUSINESS,b'\x00\x01%i\x00\x00\xff\xec\xf4\x98w\xa4\x13A...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,25,10274,0,516.871604,211.853018,259,1.0,1.0,1.0,1.0,...,BUSINESS,b'\x00\x01%i\x00\x002\x94\xe9\x8cA\xaa\x13Ao\x...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,26,10273,1,567.061442,25.452744,259,1.0,1.0,1.0,1.0,...,BUSINESS,b'\x00\x01%i\x00\x00U\x17\xcew?\xa5\x13Ax0b#n\...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,27,10274,0,350.260614,26.077824,259,1.0,1.0,1.0,1.0,...,BUSINESS,b'\x00\x01%i\x00\x00e\x81j$g\xa6\x13A\xfb}\xf2...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,28,10274,0,734.283985,509.108151,259,1.0,1.0,1.0,1.0,...,BUSINESS,b'\x00\x01%i\x00\x00(]\xfb\x81\x00\xb0\x13A\x8...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,29,10273,1,511.632988,15.054771,259,1.0,1.0,1.0,1.0,...,BUSINESS,b'\x00\x01%i\x00\x00\xd3\xfd\xc4\xfc\xdb\xa5\x...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,30,10274,0,495.564056,25.449682,259,1.0,1.0,1.0,1.0,...,BUSINESS,b'\x00\x01%i\x00\x00\xac\x96\x82I\xa2\xa7\x13A...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148499,182611,459,1,323.939104,167.504554,2752,1.0,1.0,1.0,1.0,...,RESIDENTIAL-SINGLE,b'\x00\x01%i\x00\x00\xce\xaf\xb9\x8b\x13\x08\x...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148500,182612,464,1,133.124887,101.704880,2780,1.0,1.0,1.0,1.0,...,RESIDENTIAL-SINGLE,b'\x00\x01%i\x00\x00\x07\x18v\xc0t\x16\x0eA$2t...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148501,182614,464,0,938.407128,186.627515,2752,1.0,1.0,1.0,1.0,...,RESIDENTIAL-SINGLE,b'\x00\x01%i\x00\x00\xbd\x84@\xdf\x05\r\x0eAa\...,4195.0,2.012000e+12,182614.0,5.0,3.0,4.0,1.0,77600.0
148502,182615,464,1,566.482052,2.727448,2780,1.0,1.0,1.0,1.0,...,RESIDENTIAL-SINGLE,b'\x00\x01%i\x00\x00\xe1@j\xf2\xf5\x12\x0eA\x1...,4197.0,2.013000e+12,182615.0,2.0,0.0,1.0,1.0,33000.0
148503,182617,464,0,435.919617,128.950485,2752,1.0,1.0,1.0,1.0,...,RESIDENTIAL-SINGLE,b'\x00\x01%i\x00\x00\xc5-\xebB[\x0e\x0eAI/\xe8...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148504,182618,464,1,1131.551580,206.707920,2780,1.0,1.0,1.0,1.0,...,RESIDENTIAL-SINGLE,b'\x00\x01%i\x00\x00\xdc\xaf\x11R\xce\x18\x0eA...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148505,182623,457,0,290.476718,103.360349,2780,1.0,1.0,1.0,1.0,...,RESIDENTIAL-SINGLE,"b'\x00\x01%i\x00\x00\xc0cP\xa0!\x15\x0eA\x0eR,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148506,182627,262,1,853.259273,157.397859,2744,1.0,1.0,1.0,1.0,...,RESIDENTIAL-SINGLE,b'\x00\x01%i\x00\x00\xeb%k\xc3}\xaa\x0eA:\xbc\...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148507,182628,262,1,1032.642075,312.831023,2753,1.0,1.0,1.0,1.0,...,RESIDENTIAL-SINGLE,b'\x00\x01%i\x00\x00ED]\x07<\xa3\x0eA\xbf@\x9c...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148508,182631,455,0,2310.074547,306.252887,2752,1.0,1.0,1.0,1.0,...,RESIDENTIAL-SINGLE,b'\x00\x01%i\x00\x00\x8d\x17S[\x9c\xcb\rAU\x96...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148509,182632,455,1,1378.247026,5.365943,2752,1.0,1.0,1.0,1.0,...,RESIDENTIAL-SINGLE,b'\x00\x01%i\x00\x00\\\xed\xad\xee\xb6\xae\rA\...,4192.0,2.012000e+12,182632.0,5.0,2.0,5.0,1.0,95700.0
148510,182633,457,0,4023.404370,19.592795,2780,1.0,1.0,1.0,1.0,...,RESIDENTIAL-SINGLE,b'\x00\x01%i\x00\x00\xbbqT\xf3\x1e\x13\x0eA\xb...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148511,182634,454,1,7223.672532,190.545269,2752,1.0,1.0,1.0,1.0,...,RESIDENTIAL-SINGLE,b'\x00\x01%i\x00\x00\xdb\x9d\xa9\xe2w\xd7\rA~\...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148512,182637,455,0,486.857583,109.150358,2752,1.0,1.0,1.0,1.0,...,RESIDENTIAL-SINGLE,b'\x00\x01%i\x00\x00\x9f\x8c!a\xe0\x96\rAnU\x9...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148513,182646,10783,0,118.060067,161.911807,442,1.0,1.0,1.0,1.0,...,ALL,b'\x00\x01%i\x00\x00\xb7\xcc\xa9\xa7uc\x13A\x0...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148514,182647,110488,1,283.370321,96.707525,2160,1.0,1.0,1.0,1.0,...,ALL,b'\x00\x01%i\x00\x00\xd5v\xfc\x9f\xa4\xc9\x10A...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148515,182648,24385,1,0.000000,5613.431510,3001,1.0,1.0,1.0,1.0,...,ALL,b'\x00\x01%i\x00\x00\xd0]\xb5\x18\nj\x16A\xc6c...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148516,182649,23216,1,6302.542678,5488.461064,3002,1.0,1.0,1.0,1.0,...,ALL,b'\x00\x01%i\x00\x00s1\x15Z0K\x14ADI\x1f\xfd\x...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148517,182650,6331,0,1196.970264,5879.938437,3004,1.0,1.0,1.0,1.0,...,ALL,b'\x00\x01%i\x00\x00\x1d\xc4\x14\x1b\x13\x81\x...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148518,182651,736,0,3734.762300,6265.045616,3005,1.0,1.0,1.0,1.0,...,ALL,b'\x00\x01%i\x00\x00H\xe3+n\xb2\xa7\x0eA\x05hU...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148519,182652,424,0,0.000000,4526.603751,3006,1.0,1.0,1.0,1.0,...,ALL,b'\x00\x01%i\x00\x00AZYC\xff\xf9\x0cA3\xab\x80...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148520,182653,455,0,0.000000,4578.086201,3007,1.0,1.0,1.0,1.0,...,ALL,b'\x00\x01%i\x00\x00@\xb3rO\xdb\xfc\x0cA\x1c7]...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148521,182654,273,0,0.000000,4857.044394,3008,1.0,1.0,1.0,1.0,...,ALL,b'\x00\x01%i\x00\x00h\xbb\x8c\xe8\xad\xff\x0cA...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148522,182655,83,0,0.000000,4054.258969,3009,1.0,1.0,1.0,1.0,...,ALL,b'\x00\x01%i\x00\x00k!\xaa\xd7\xe7\xf2\x0cA\xf...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148523,182656,1740,0,0.000000,3487.461679,3011,1.0,1.0,1.0,1.0,...,ALL,b'\x00\x01%i\x00\x00?|\xd1\x013\xda\x0fA\x01G\...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148524,182657,845,0,939.486592,3512.802283,3013,1.0,1.0,1.0,1.0,...,ALL,b'\x00\x01%i\x00\x00\x99/\xb6=\x02\xdf\x10A+\x...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148525,182658,20628,1,0.000000,5140.813921,3015,1.0,1.0,1.0,1.0,...,ALL,b'\x00\x01%i\x00\x00\x91\x87\xfe\xfbEw\x13A-\x...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148526,182659,23257,0,3168.962453,5189.129143,3016,1.0,1.0,1.0,1.0,...,ALL,b'\x00\x01%i\x00\x00\xc2al\x8f\xf7/\x15A@\x8c\...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148527,182660,13871,0,510.699377,1796.802178,3017,1.0,1.0,1.0,1.0,...,ALL,"b'\x00\x01%i\x00\x00&3""q\x1a5\x14A\xc1\xd5\xa8...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148528,182661,24592,0,49.684342,1978.164660,3018,1.0,1.0,1.0,1.0,...,ALL,b'\x00\x01%i\x00\x00\xbaeY\xd2\x01\x8a\x17A\x9...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
activity

,id,seq_num,location_id,start_time,duration,mode,type,person,trip
0,1,2,85589,539.0,1064.0,AUTO,SHOP-OTHER,24481,1
1,2,2,8692,557.0,26680.0,AUTO,WORK,29840,2
2,3,2,107445,557.0,8937.0,AUTO,PART_WORK,38959,3
3,4,6,110325,635.0,489.0,AUTO,PICKUP-DROPOFF,8322,4
4,5,2,107662,653.0,444.0,AUTO,SHOP-OTHER,21121,5
5,6,3,15628,678.0,330.0,HOV,SHOP-MAJOR,6268,6
6,7,2,67569,683.0,25045.0,AUTO,WORK,12772,7
7,8,4,160390,701.0,330.0,AUTO,SHOP-MAJOR,17498,8
8,9,3,69112,748.0,330.0,HOV,SHOP-MAJOR,20712,9
9,10,3,146357,751.0,330.0,TRANSIT,SHOP-OTHER,5446,10
10,11,3,49806,767.0,504.0,AUTO,SHOP-OTHER,45243,11
11,12,2,107686,778.0,8640.0,WALK,PART_WORK,24533,12
12,13,2,123367,803.0,32512.0,AUTO,WORK,40596,13
13,14,2,110325,824.0,25200.0,HOV,SCHOOL,8324,14
14,15,2,3650,874.0,44602.0,BIKE,WORK,31809,15
15,16,2,2898,941.0,880.0,AUTO,SHOP-OTHER,6904,16
16,17,2,10803,952.0,25200.0,HOV,SCHOOL,22704,17
17,18,4,134081,1019.0,330.0,AUTO,SHOP-OTHER,37208,18
18,19,5,10803,1031.0,300.0,AUTO,PICKUP-DROPOFF,22701,19
19,20,2,110427,1037.0,32646.0,AUTO,WORK,9108,20
20,21,2,131003,1037.0,36056.0,AUTO,WORK,7542,21
21,22,3,93584,1043.0,895.0,AUTO,SHOP-OTHER,14298,22
22,23,3,129438,1043.0,84949.0,AUTO,PERSONAL,41198,23
23,24,2,9177,1055.0,21600.0,AUTO,WORK,30301,24
24,25,3,75419,1061.0,330.0,AUTO,SHOP-OTHER,16470,25
25,26,2,134686,1061.0,28800.0,AUTO,WORK,38756,26
26,27,3,82423,1067.0,910.0,AUTO,SHOP-OTHER,25117,27
27,28,3,154301,1079.0,2059.0,AUTO,SHOP-OTHER,16972,28
28,29,2,11696,1091.0,28800.0,AUTO,WORK,34621,29
29,30,3,81971,1097.0,85023.0,AUTO,PERSONAL,23673,30
...,...,...,...,...,...,...,...,...,...
175849,175850,112,99269,86051.0,350.0,AUTO,HOME,34101,175850
175850,175851,109,46367,86057.0,344.0,AUTO,HOME,32220,175851
175851,175852,3,131040,86057.0,330.0,AUTO,SHOP-OTHER,36144,175852
175852,175853,104,32320,86060.0,341.0,HOV,HOME,35197,175853
175853,175854,106,22485,86063.0,338.0,AUTO,HOME,13860,175854
175854,175855,105,129153,86063.0,338.0,AUTO,HOME,40647,175855
175855,175856,106,141970,86063.0,338.0,AUTO,HOME,28471,175856
175856,175857,106,86208,86069.0,332.0,AUTO,HOME,24486,175857
175857,175858,107,94858,86069.0,332.0,AUTO,HOME,39026,175858
175858,175859,105,129998,86069.0,332.0,AUTO,HOME,36595,175859
175859,175860,108,62338,86074.0,327.0,HOV,HOME,1139,175860
175860,175861,102,135657,86075.0,326.0,AUTO,HOME,41111,175861
175861,175862,107,60241,86075.0,326.0,AUTO,HOME,22870,175862
175862,175863,103,98841,86075.0,326.0,AUTO,HOME,34064,175863
175863,175864,106,79419,86075.0,326.0,AUTO,HOME,8604,175864
175864,175865,108,166119,86076.0,325.0,AUTO,HOME,43848,175865
175865,175866,104,72804,86078.0,323.0,HOV,HOME,860,175866
175866,175867,105,95466,86078.0,323.0,HOV,HOME,19506,175867
175867,175868,104,71380,86081.0,320.0,AUTO,HOME,12245,175868
175868,175869,104,123105,86081.0,320.0,AUTO,HOME,43062,175869
175869,175870,106,129356,86084.0,317.0,HOV,HOME,39609,175870
175870,175871,108,56607,86086.0,315.0,HOV,HOME,16203,175871
175871,175872,106,126276,86087.0,314.0,AUTO,HOME,42043,175872
175872,175873,106,94463,86092.0,309.0,WALK,HOME,38729,175873
175873,175874,104,175786,86097.0,304.0,HOV,HOME,11376,175874
175874,175875,104,122543,86097.0,304.0,HOV,HOME,39858,175875
175875,175876,106,41271,86097.0,304.0,HOV,HOME,45195,175876
175876,175877,106,111076,86098.0,303.0,HOV,HOME,8933,175877
175877,175878,104,46058,86098.0,303.0,HOV,HOME,31879,175878
175878,175879,106,106956,86099.0,302.0,AUTO,HOME,38663,175879

In [21]:
households.columns

Index(['household', 'hhold', 'location', 'persons', 'workers', 'vehicles',
       'type', 'income'],
      dtype='object')

In [22]:
people.columns

Index(['person', 'id', 'school_location_id', 'work_location_id', 'age',
       'worker_class', 'education', 'industry', 'employment', 'gender',
       'income', 'journey_to_work_arrival_time', 'journey_to_work_mode',
       'journey_to_work_travel_time', 'journey_to_work_vehicle_occupancy',
       'marital_status', 'race', 'school_enrollment', 'school_grade_level',
       'work_hours', 'household'],
      dtype='object')

In [23]:
locations.columns

Index(['location', 'link', 'dir', 'offset', 'setback', 'zone', 'truck_org',
       'truck_des', 'auto_org', 'auto_des', 'transit', 'area_type', 'notes',
       'census_zone', 'x', 'y', 'land_use', 'geo', 'household', 'hhold',
       'location:1', 'persons', 'workers', 'vehicles', 'type', 'income'],
      dtype='object')

In [24]:
households.persons

0        1
1        1
2        1
3        3
4        3
5        2
6        1
7        1
8        1
9        1
10       2
11       3
12       2
13       2
14       1
15       4
16       2
17       2
18       2
19       4
20       1
21       3
22       4
23       4
24       2
25       2
26       1
27       1
28       5
29       1
        ..
18910    1
18911    2
18912    2
18913    1
18914    2
18915    1
18916    1
18917    1
18918    3
18919    3
18920    3
18921    4
18922    4
18923    1
18924    1
18925    1
18926    1
18927    1
18928    1
18929    2
18930    2
18931    2
18932    2
18933    3
18934    2
18935    1
18936    4
18937    3
18938    2
18939    3
Name: persons, Length: 18940, dtype: int64

In [25]:
# count up all the number of people by looking at the households data - should match the number of people data
households.persons.mean()

2.4520063357972544

In [26]:
# find the max person number, should match sum of people in households if we don't count homeless
households["persons"]

0        1
1        1
2        1
3        3
4        3
5        2
6        1
7        1
8        1
9        1
10       2
11       3
12       2
13       2
14       1
15       4
16       2
17       2
18       2
19       4
20       1
21       3
22       4
23       4
24       2
25       2
26       1
27       1
28       5
29       1
        ..
18910    1
18911    2
18912    2
18913    1
18914    2
18915    1
18916    1
18917    1
18918    3
18919    3
18920    3
18921    4
18922    4
18923    1
18924    1
18925    1
18926    1
18927    1
18928    1
18929    2
18930    2
18931    2
18932    2
18933    3
18934    2
18935    1
18936    4
18937    3
18938    2
18939    3
Name: persons, Length: 18940, dtype: int64

In [27]:
# list out the different land use types
locations.land_use.unique()

array(['SPECIAL_GEN', 'BUSINESS', 'CIVIC', 'INDUSTRY', 'RESIDENTIAL-MULTI',
       'RECREATION', 'RESIDENTIAL-SINGLE', 'AGRICULTURE', 'ALL'], dtype=object)

In [28]:
# count up the number of locations that are business
locations.land_use[locations.land_use == 'BUSINESS'].count()

28002

In [29]:
# count the number of multifamiliy residential
locations.land_use[locations.land_use == 'RESIDENTIAL-MULTI'].count()

5727

In [30]:
locations.land_use[locations.land_use == 'RESIDENTIAL-SINGLE'].count()

86762

In [31]:
locations.land_use[locations.land_use == 'CIVIC'].count()

13535

In [32]:
locations.land_use[locations.land_use == 'INDUSTRY'].count()

7195

In [33]:
locations.land_use[locations.land_use == 'RECREATION'].count()

4967

In [34]:
locations.land_use[locations.land_use == 'ALL'].count()

16

In [35]:
locations.land_use[locations.land_use == 'AGRICULTURE'].count()

2256

In [46]:
beginning_location = pd.merge(household, person, on='household', how='left')

NameError: name 'household' is not defined